# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Drawings
description: > # this means to ignore newlines until "baseurl:"
  Way back when I was only a whipper snapper I was casting around for something to make a website about and I realised that one thing I did a lot was draw cartoons. So I drew some and put them online. This is that.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://drawings.ghijklmno.net" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
